export interface IClue {
  id: number,
  merchantId: number,
  message: string,
  customerName: string,
  customerPhone: string,
  plateNo: string,
  brandName: string,
  carStatus: number,
  repairStatus: number,
  insCode: string,
  orderSource: number,
  reportNo: string,
  reportDate: string,
  reportAddress: string,
  userId: number | null,
  status: number,
  creator: number,
  createTime: string,
  modifier: string,
  updateTime: string
}
